# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: my_db_dev
  pool: 5
  username: blogger
  password: secret

test:
  adapter: postgresql
  encoding: unicode
  database: my_db_test
  pool: 5
  username: blogger
  password: secret

production:
  adapter: postgresql
  encoding: unicode
  database: my_db_production
  pool: 5
  username: blogger
  password: secret
